### ISSUE TITLE
SVG translate not working with react-native@0.29.0 react-native-svg@3.0.0 

### ISSUE THREAD

**Issue by bjornbrynjar** [magicismight/react-native-svg#88]
I there..

I am using react-native-svg to render charts but there seems to be problem with the svg translate attribute.. as it doesn't work. 

Here is my package.json:
```
"react": "^15.2.0",
"react-native": "^0.29.0",
"react-native-svg": "^3.0.0"
```
Here is my render method:
```
render() {
  return (
      <View >
        <Svg height="640" width="360">
          <Circle transform="translate(200, 200)"
              cx="50"
              cy="50"
              r="45"
              stroke="blue"
              strokeWidth="2.5"
              fill="green"
          />
          <Rect translate="rotate(45)"
              x="15"
              y="15"
              width="70"
              height="70"
              stroke="red"
              strokeWidth="2"
              fill="yellow"
            />
        </Svg>
      </View>
    );
  }
```
I made sure everything is in place for react-native@0.29.0 in line with https://github.com/magicismight/react-native-svg/issues/50#issuecomment-222893637

And here is a screenshot:
![screenshot_2016-07-27-09-11-06_com getease](https://cloud.githubusercontent.com/assets/10855937/17170137/5727857c-53da-11e6-8f30-cbb83e531a57.png)

**Comment by magicismight** [comment]
Thanks for reporting this.
transform prop have been fixed in 4.0.0-rc.
And we have changed transform prop to something like this
```
          <Circle
              transform={{scale:0.5,translate:'200, 200'}}
              cx="50"
              cy="50"
              r="45"
              stroke="blue"
              strokeWidth="2.5"
              fill="green"
          />

or this can do the same
          <Circle
              scale="0.5"
              translate="200, 200"
              cx="50"
              cy="50"
              r="45"
              stroke="blue"
              strokeWidth="2.5"
              fill="green"
          />
```

**Comment by bjornbrynjar** [comment]
I am afraid translate still doesn't work after I updated to latest versions:

```
"react": "^15.2.0",
 "react-native": "^0.30.0",
 "react-native-svg": "^4.0.0-rc"
```


Check out the code below - before and after putting the transform variable in place:

BEFORE:
![screenshot_2016-07-27-23-22-15_com getease](https://cloud.githubusercontent.com/assets/10855937/17196370/9401c68c-5453-11e6-9c25-4d130dde72c0.png)

AFTER:
![screenshot_2016-07-27-23-33-45_com getease](https://cloud.githubusercontent.com/assets/10855937/17196376/a990a770-5453-11e6-9271-18295b9e47c2.png)

Hence, rotate and scale both works.. translate doesn't :(


```
render() {
   const dx = 80;
    const dy = 80;
    const rotateby = 5;
    const scaleby = 1.2;
    const transform = {translate:`'${dx}, ${dy}'`,rotate:`${rotateby}`, scale:`${scaleby}`};
    return (
      <View >
      <Svg height="640" width="360">
        <Circle
          {...{transform}}
            cx="50"
            cy="50"
            r="45"
            stroke="blue"
            strokeWidth="2.5"
            fill="green"
        />
        <Rect
         {...{transform}}
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
          />
      </Svg>
      </View>
    );
  }
```

**Comment by magicismight** [comment]
You had extra single quotes in translate

**Comment by bjornbrynjar** [comment]
You are right that's it!  👍

**Comment by carly-litchfield-zocdoc** [comment]
I had this problem too, and using `transform={{ translate:'200, 200' }}` instead of `transform="translate(200, 200)` fixed it 😄
